//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testably.Abstractions.Migration.Analyzers {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Testably.Abstractions.Migration.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Migrate System.IO.Abstractions MockFileSystem to Testably.Abstractions.
        /// </summary>
        internal static string TestablyAbstractionsMigration001CodeFixTitle {
            get {
                return ResourceManager.GetString("TestablyAbstractionsMigration001CodeFixTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Migrate MockFileSystem usages from System.IO.Abstractions to Testably.Abstractions..
        /// </summary>
        internal static string TestablyAbstractionsMigration001Description {
            get {
                return ResourceManager.GetString("TestablyAbstractionsMigration001Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System.IO.Abstractions MockFileSystem should be migrated to Testably.Abstractions..
        /// </summary>
        internal static string TestablyAbstractionsMigration001MessageFormat {
            get {
                return ResourceManager.GetString("TestablyAbstractionsMigration001MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System.IO.Abstractions MockFileSystem should be migrated..
        /// </summary>
        internal static string TestablyAbstractionsMigration001Title {
            get {
                return ResourceManager.GetString("TestablyAbstractionsMigration001Title", resourceCulture);
            }
        }
    }
}
